version: '3'

networks:
   listingapp:


services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes: 
       - /apps/opt/mongo:/var/lib/mongo
    ports:
       - '29017:27017'
    networks:
      - listingapp   
