version: '3'

networks:
    listingapp:

services:

  gateway:
    container_name: gateway
    image: listing-app/gateway:${version}
    restart: always
    environment:
            NATS_SERVER_URL: nats-server:4222

    working_dir: /gateway
    networks:
      - listingapp
    ports:
      - '80:3000'
