---

- hosts: 127.0.0.1
  tasks:
    - name: "Building service: {{ svcname }}, version: {{ version }}"
      shell: "cd ../{{ svcname }}/ && docker build -t listing-app/{{ svcname }}:{{ version }} ."

    - name: something
      shell: pwd
      register: pth
    - debug: var=pth.stdout_lines

    - name: "Deploying service: {{ svcname }}, version: {{ version }}"
      shell: |
          "version={{ version }} docker-compose -f ../deploy/docker-compose-{{ svcname }}.yaml down"
          "version={{ version }} docker-compose -f ../deploy/docker-compose-{{ svcname }}.yaml up -d"
      ignore_errors: yes
