- name: Git clone repo
  git: 
    repo: git@github.com:vijaypsamy/listing-app.git
    dest: /apps/opt/workspace
    version: master
    accept_hostkey: yes

- name: Install curl
  shell: sudo yum install curl -y  

- name: Install Docker
  shell: |
          sudo yum install -y yum-utils device-mapper-persistent-data lvm2
          sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
          sudo yum -y install https://download.docker.com/linux/centos/7/x86_64/stable/Packages/containerd.io-1.2.6-3.3.el7.x86_64.rpm
          sudo groupadd docker
          sudo usermod -aG docker ec2-user
          sudo yum install -y docker-ce docker-ce-cli containerd.io
          sudo systemctl enable docker
          sudo systemctl start docker

- name: Install Docker Compose
  shell: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.25.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
