- name: Build gateway and listing services
  shell: |
          cd ../gateway/ && docker build -t listing-app/gateway:v1 .
          cd ../accomodation-listing-service/ && docker build -t listing-app/accomodation-listing-service:v1 .

- name: Deploy gateway, accomodation-listing-service, nats-server, mongodb
  shell: |
          version=v1 docker-compose -f ../deploy/docker-compose-mongo.yaml up -d
          version=v1 docker-compose -f ../deploy/docker-compose-nats-server.yaml up -d
          version=v1 docker-compose -f ../deploy/docker-compose-listing.yaml up -d
          version=v1 docker-compose -f ../deploy/docker-compose-gateway.yaml up -d
